#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	
	if ((fp = fopen("schedule.dat", "r")) == NULL)
	{
		printf("File error\n");
		return -1;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	while (fscanf(fp, "%s, %s, %i, %i, %i\n", name, place, &type, &month, &day) != EOF)
	{	
		//generate genSchedInfo structure by genSchedInfo function
		schedInfo = sched_genSchedInfo(name, place, type, month, day);
		
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	
	//close the file pointer
	fclose(fp);
	
	printf("Read done! %i schedules are read\n\n", list_len(list));
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		printf("----------------------------------------\n");
		printf("1. print all the schdules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n"); 
		printf("----------------------------------------\n");
		
		//4. get option from keyboard
		printf("select an option : \n");
		scanf("%d", &option);
		
		
		switch(option)
		{
			case 1: //print all the schedules
				cnt=1;
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					// print count and each scheduling info element
					printf("----------------------------------------\n");
					printf("%i.", cnt);
					sched_print(schedInfo);
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					cnt ++;
					printf("----------------------------------------");
				}
				
				break;
			
			case 2:
				cnt=1;
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//print scheduling info elements matching to the month
					if(month == sched_getMonth(schedInfo))
					{
						printf("----------------------------------------\n");
						printf("%i.", cnt);
						sched_print(schedInfo);
						cnt++;
						printf("----------------------------------------\n");
					}
					else
					{
						printf("----------------------------------------\n");
						printf("no schedule\n");
						printf("----------------------------------------\n");
					}
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
				
				}
				
				break;
				
			case 3:
				cnt=1;
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					if(place == sched_getPlace(schedInfo) == 0)
					{
						printf("----------------------------------------\n");
						printf("%i.", cnt);
						sched_print(schedInfo);
						cnt++;
						printf("----------------------------------------\n");
					}
					else
					{
						printf("----------------------------------------\n");
						printf("no place\n");
						printf("----------------------------------------\n");
					}
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
				
				}
				
				break;
				
			case 4:
				cnt=1;
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (sched_convertType(typeName) >= 0)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//print scheduling info elements matching to the place
						printf("----------------------------------------\n");
						printf("%i.", cnt);
						sched_print(schedInfo);
						cnt++;
						printf("----------------------------------------\n");
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
